name: Swagger to Markdown using widdershins

on:
  push:
    paths:
      - '**.yaml' # Replace with the path to your Swagger spec file

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install -g widdershins
      - name: Generate documentation
        run: widdershins --search false --language_tabs 'shell:Shell' 'javascript:JavaScript' --summary ${{values.swaggerUrl | dump}} -o docs/all-apis.md
      - name: Commit documentation
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Update documentation'
          add: '*.md'
          #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 Name backstage_git_action 
          github_token: ${{ secrets.GIT_ACTION }}
